name: Linting Python
# https://medium.com/swlh/enhancing-code-quality-with-github-actions-67561c6f7063

on:
  push:
    branches:
      - "main"
    paths:
      - '**.py'
      - requirements.txt
  pull_request:
    paths:
      - '**.py'
      - requirements.txt

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  checks: write
  contents: write

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Python linters
        run: pip install flake8 pylint

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_args: |
            --ignore=E501
          continue_on_error: false
          pylint: true
          # https://github.com/pylint-dev/pylint/issues/8138
          pylint_args: |
            --disable=missing-module-docstring \
            --disable=missing-class-docstring \
            --disable=missing-function-docstring \
            --disable=line-too-long \
            --disable=too-few-public-methods \
            --disable=cyclic-import
